[context.production]
  command = "yarn add sharp --ignore-engines && yarn build"
  publish = ".next"

[context.staging]
  command = "yarn add sharp --ignore-engines && yarn build"
  publish = ".next" 

[functions]
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**/*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"