import './globals.css';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { draftMode, headers } from 'next/headers';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/sb-ui/ThemeProvider';
import { Toaster } from '@/components/ui/sonner';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import Script from 'next/script';
import Link from 'next/link';
import CookieConsent from './lib/consent';
import AuthState from './components/sb-ui/AuthState';
config.autoAddCss = false;

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  async function clearDraft() {
    'use server';
    draftMode().disable();
  }
  const pathname = headers().get('x-pathname') as string;
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {draftMode().isEnabled ? (
            <section className="draftMode">
              <Link
                prefetch={false}
                href={`/api/exit-preview?redirect=${pathname}`}
              >
                Exit Draftmode
              </Link>
            </section>
          ) : (
            <></>
          )}
          {children}
          <CookieConsent />
        </ThemeProvider>
        <Toaster />
        <AuthState />
        <Script
          src="https://kit.fontawesome.com/fd72af6caf.js"
          crossOrigin="anonymous"
        ></Script>
      </body>
    </html>
  );
}
